---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: tenants.qsmith.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: qsmith.com
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Tenant
    # singular name to be used as an alias on the CLI and for display
    singular: tenant
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: tenants
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - tnt
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # each version can be enabled/disabled by Served flag.
      served: true
      # one and only one version must be marked as the storage version.
      storage: true
      # list of additional columns to show to user.
      additionalPrinterColumns:
      - name: Namespace
        type: string
        jsonPath: .metadata.namespace
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
      - name: Tenant name
        type: string
        jsonPath: .spec.name
      # schema used for validation
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
            status:
              type: object
              default: {}
              properties:
                observedGeneration:
                  type: integer
                  default: 0

