---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-kso
  namespace: demo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-kso
rules:
- apiGroups: ["qsmith.com"]
  resources: ["tenants"]
  verbs: ["list", "get", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-kso
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-kso
subjects:
  - kind: ServiceAccount
    name: sa-kso
    namespace: demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kso
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kso
  template:
    metadata:
      labels:
        app: kso
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 20
      serviceAccountName: sa-kso
      containers:
      - name: hooks
        imagePullPolicy: Never
        image: kso:latest
        resources:
          requests:
            cpu: "150m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"